version: "3"

services:
  node:
    container_name: avax
    image: senseinode/avalanche:1.0
    restart: unless-stopped
    env_file: .env
    ports:
      - "9650:9650"
      - "9651:9651"
    volumes:
      - ./avalanche:/root/.avalanchego
    command: 
      - --network-id=fuji
      - --http-host=
      - --public-ip=${NODE_PUB_IP}
